# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: check-merge-conflict
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args:
          - --py3-plus
          - --keep-runtime-typing
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.3
    hooks:
      - id: pylint
        args: ["--disable=import-error", "--rcfile=pyproject.toml"]

  - repo: local
    hooks:
    - id: update-requirements-txt
      name: update-requirements-txt
      description: 'Generate requirements.txt based on poetry.lock'
      entry: poetry
      args: [export, --without-hashes, --without, dev, --format, requirements.txt, --output, requirements/requirements.txt]
      language: system
      pass_filenames: false
  - repo: local
    hooks:
    - id: update-requirements-txt
      name: update-requirements-txt
      description: 'Generate requirements.txt based on poetry.lock'
      entry: poetry
      args: [export, --without-hashes, --with, dev, --format, requirements.txt, --output, requirements/requirements-dev.txt]
      language: system
      pass_filenames: false
ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit hooks
  autoupdate_commit_msg: ⬆️ [pre-commit.ci] Auto update from pre-commit hooks
